/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class P2P_SDK */

#ifndef _Included_P2P_SDK
#define _Included_P2P_SDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     P2P_SDK
 * Method:    Init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_P2P_SDK_Init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     P2P_SDK
 * Method:    UnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_P2P_SDK_UnInit
  (JNIEnv *, jclass);

/*
 * Class:     P2P_SDK
 * Method:    Login
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_P2P_SDK_Login
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     P2P_SDK
 * Method:    Logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_P2P_SDK_Logout
  (JNIEnv *, jclass);

/*
 * Class:     P2P_SDK
 * Method:    ModifyPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_P2P_SDK_ModifyPassword
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     P2P_SDK
 * Method:    RealPlay
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_P2P_SDK_RealPlay
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     P2P_SDK
 * Method:    StopPlay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_P2P_SDK_StopPlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     P2P_SDK
 * Method:    GetBmp32Frame
 * Signature: (III[I[I)I
 */
JNIEXPORT jint JNICALL Java_P2P_SDK_GetBmp32Frame
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     P2P_SDK
 * Method:    GetH264
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_P2P_SDK_GetH264
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
